spring:
  application:
    name: crss
  liquibase:
    change-log: classpath:liquibase/master.xml
    contexts: "develop"
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/crss?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: crss
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
file-system:
  storage:
    images:
      recipe:
        images/recipe/
      country:
        ./server/src/main/resources/images/country/
crss:
  web-config:
    allowed-origins:
      http://localhost:4200
  app:
    jwtSecret: crssSecretKey
    jwtExpirationMs: 86400000